version: "3.11"
services:
  api:
    container_name: study-mate-server
    restart: always
    image: joaopdss/study-mate-server:next
    build:
      context: .
    env_file: .env
    environment:
      FLASK_APP: app.py
      PYTHONUNBUFFERED: 1
      SSL_CERT_PATH: /etc/letsencrypt/archive/api-study-mate.luna-fashion-ai.com/fullchain1.pem
      SSL_KEY_PATH: /etc/letsencrypt/archive/api-study-mate.luna-fashion-ai.com/privkey1.pem
    command: ["python", "app.py"]
    ports:
      - 5003:5003
    volumes:
      - .:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro